FROM composer:1.8 AS composer

COPY ./composer.json composer.json
COPY ./composer.lock composer.lock

RUN composer install \
        --no-suggest \
        --no-interaction \
        --ignore-platform-reqs \
        --no-progress \
        --optimize-autoloader


FROM php:8.1-fpm-alpine

COPY . /htdocs
COPY ./docker/php.ini /usr/local/etc/php/php.ini

COPY --from=composer /app/vendor/ /htdocs/vendor/

#WORKDIR /htdocs
